apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 172.16.1.11, internalAddress: 172.16.1.11, user: ubuntu, password: Qcloud@123}
  - {name: node2, address: 172.16.1.12, internalAddress: 172.16.1.12, user: ubuntu, password: Qcloud@123}
  - {name: node3, address: 172.16.1.13, internalAddress: 172.16.1.13, user: ubuntu, password: Qcloud@123}
  roleGroups:
    etcd:
    - node1
    master:
    - node1
    worker:
    - node1
    - node2
    - node3
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    type: k3s
    version: v1.20.7
    clusterName: cluster.local
  network:
    plugin: calico
    calico:
      vethMTU: 1440
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons:
    - name: rook-ceph-cluster
      namespace: rook-ceph
      sources:
        chart:
          name: ceph-cluster
          path: ./charts
          values:
          - enableHA=true
          - ceph.image.repository=dockerhub.kubekey.local:5000/ceph/ceph
          - rook-ceph.image.repository=dockerhub.kubekey.local:5000/rook/ceph
          - rook-ceph.csi.cephcsi.image=dockerhub.kubekey.local:5000/kubespheredev/cephcsi:v3.3.1
          - rook-ceph.csi.registrar.image=dockerhub.kubekey.local:5000/kubespheredev/csi-node-driver-registrar:v2.0.1
          - rook-ceph.csi.provisioner.image=dockerhub.kubekey.local:5000/kubespheredev/csi-provisioner:v2.1.0
          - rook-ceph.csi.snapshotter.image=dockerhub.kubekey.local:5000/kubespheredev/csi-snapshotter:v4.0.0
          - rook-ceph.csi.attacher.image=dockerhub.kubekey.local:5000/kubespheredev/csi-attacher:v3.1.0
          - rook-ceph.csi.resizer.image=dockerhub.kubekey.local:5000/kubespheredev/csi-resizer:v1.1.0
          - snapshot-controller.repository=dockerhub.kubekey.local:5000/csiplugin/snapshot-controller
    - name: ks-installer
      namespace: kubesphere-system
      sources:
        chart:
          name: ks-installer
          path: ./charts
          values:
            - registry=dockerhub.kubekey.local:5000
            - image.tag=ksv-v1.0.4-CE
            - common.minioVolumeSize=100Gi
            - virtualization.useEmulation=false
            - virtualization.cpuAllocationRatio=1
